/**
 * Turning a verification report into something a router can enforce.
 *
 * A verdict you have to act on by hand is a verdict you act on once. These
 * exporters produce the exact file formats OpenWrt already consumes, so the
 * outcome of a CSV check can become a live DNS block or a policy-routing rule
 * without retyping anything.
 *
 * Formats, and who eats them:
 *   dnsmasq-block   `address=/host/`         — dnsmasq, NXDOMAIN-style blocking
 *   hosts           `0.0.0.0 host`           — /etc/hosts, Pi-hole, anything
 *   domains         one name per line        — adblock-fast, pbr, generic tooling
 *   dnsmasq-nftset  `nftset=/host/4#inet#fw4#name` — OpenWrt 22.03+ (fw4/nftables)
 *   dnsmasq-ipset   `ipset=/host/name`       — OpenWrt 21.02 and older (iptables)
 *   nftables        an `nft` set of addresses — direct firewall use
 *   pbr             a ready `/etc/config/pbr` policy stanza
 *
 * The nftset/ipset variants are the interesting ones: they let dnsmasq add every
 * address a name resolves to into a named set as it is resolved, which is how
 * the pbr package routes traffic by domain rather than by address.
 */

const HEADER = (title, meta) => [
  `# ${title}`,
  `# generated by urlscan-verify at ${meta.generatedAt}`,
  `# source: ${meta.source || "CSV verification"}`,
  `# entries: ${meta.count}`,
  `# verdicts included: ${meta.severities.join(", ")}`,
  "#",
  "# Review before deploying. Verdicts come from urlscan submitter tags and",
  "# structural analysis, not from an audited feed — a false positive here",
  "# becomes a name your network can no longer reach.",
  "",
];

/** Pick the entries a blocklist should contain. */
export function selectEntries(report, { severities = ["critical"], includeIPs = true } = {}) {
  const wanted = new Set(severities);
  return {
    hosts: report.hosts.filter((h) => wanted.has(h.severity)).map((h) => h.host),
    ips: includeIPs
      ? report.ips.filter((i) => wanted.has(i.severity) && i.routable !== false).map((i) => i.ip)
      : [],
  };
}

/**
 * Build every export format at once.
 *
 * @param {object} report
 * @param {object} opts
 * @param {string[]} [opts.severities]  which verdicts to include (default critical only)
 * @param {string}   [opts.setName]     nftables/ipset set name
 * @param {string}   [opts.source]      free text recorded in the file headers
 * @param {string}   [opts.interface]   pbr policy interface, e.g. `wan` or `vpn`
 * @returns {Record<string,string>} filename -> file contents
 */
export function buildExports(report, opts = {}) {
  const {
    severities = ["critical"],
    setName = "urlscan_verify",
    source = "CSV verification",
    interface: iface = "wan",
  } = opts;

  const { hosts, ips } = selectEntries(report, { severities });
  const meta = { generatedAt: report.generatedAt, source, count: hosts.length + ips.length, severities };
  // nftables set names accept letters, digits and underscores only; collapse
  // everything else rather than leaving a trailing run of separators.
  const safeSet =
    String(setName).replace(/[^A-Za-z0-9_]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 32) || "urlscan_verify";

  const files = {};

  files["domains.txt"] = [...HEADER("plain domain list", { ...meta, count: hosts.length }), ...hosts, ""].join("\n");

  files["dnsmasq-block.conf"] = [
    ...HEADER("dnsmasq blocking config — copy to /etc/dnsmasq.d/", { ...meta, count: hosts.length }),
    "# Every listed name (and its subdomains) resolves to nothing.",
    "",
    ...hosts.map((h) => `address=/${h}/`),
    "",
  ].join("\n");

  files["hosts.txt"] = [
    ...HEADER("hosts-file blocklist", { ...meta, count: hosts.length }),
    ...hosts.flatMap((h) => [`0.0.0.0 ${h}`, `:: ${h}`]),
    "",
  ].join("\n");

  files["dnsmasq-nftset.conf"] = [
    ...HEADER(`dnsmasq -> nftables set "${safeSet}" (OpenWrt 22.03+, fw4)`, { ...meta, count: hosts.length }),
    "# dnsmasq adds every address these names resolve to into the named set, so a",
    "# firewall or routing rule can match the domain without knowing its addresses.",
    "#",
    "# Create the sets first, e.g. in /etc/nftables.d/10-urlscan-verify.nft:",
    `#   set ${safeSet}   { type ipv4_addr; flags interval; }`,
    `#   set ${safeSet}6  { type ipv6_addr; flags interval; }`,
    "# then: /etc/init.d/dnsmasq restart",
    "",
    ...hosts.map((h) => `nftset=/${h}/4#inet#fw4#${safeSet},/${h}/6#inet#fw4#${safeSet}6`),
    "",
  ].join("\n");

  files["dnsmasq-ipset.conf"] = [
    ...HEADER(`dnsmasq -> ipset "${safeSet}" (OpenWrt 21.02 and older, iptables)`, { ...meta, count: hosts.length }),
    "# Requires the dnsmasq-full build with ipset support and dnsmasq_full ipset sets",
    `# created beforehand: ipset create ${safeSet} hash:ip`,
    "",
    ...hosts.map((h) => `ipset=/${h}/${safeSet}`),
    "",
  ].join("\n");

  files["nftables-addresses.nft"] = [
    ...HEADER(`nftables address set "${safeSet}_ips"`, { ...meta, count: ips.length }),
    "# Load with: nft -f nftables-addresses.nft   (or drop into /etc/nftables.d/)",
    "",
    "table inet fw4 {",
    `  set ${safeSet}_ips {`,
    "    type ipv4_addr",
    "    flags interval",
    ips.filter((i) => !i.includes(":")).length
      ? `    elements = { ${ips.filter((i) => !i.includes(":")).join(", ")} }`
      : "    # no IPv4 entries",
    "  }",
    `  set ${safeSet}_ips6 {`,
    "    type ipv6_addr",
    "    flags interval",
    ips.filter((i) => i.includes(":")).length
      ? `    elements = { ${ips.filter((i) => i.includes(":")).join(", ")} }`
      : "    # no IPv6 entries",
    "  }",
    "}",
    "",
  ].join("\n");

  files["pbr-policy.conf"] = [
    ...HEADER("OpenWrt pbr policy stanza — append to /etc/config/pbr", meta),
    "# Routes traffic for these names over the named interface. Change `interface`",
    "# to whichever wan/vpn you want this traffic to leave by, then:",
    "#   /etc/init.d/pbr restart",
    "#",
    "# pbr resolves the names through dnsmasq into an nftables set, which is why",
    "# dnsmasq-nftset.conf above pairs with this. On a large list prefer pointing",
    "# pbr at domains.txt with a `path` option rather than inlining every name.",
    "",
    "config policy",
    `\toption name '${safeSet}'`,
    `\toption interface '${iface}'`,
    "\toption dest_addr '" + hosts.slice(0, 200).join(" ") + "'",
    "\toption enabled '1'",
    "",
    hosts.length > 200 ? `# ${hosts.length - 200} further names omitted — use domains.txt with an include instead.` : "",
    "",
  ].join("\n");

  files["README.txt"] = [
    "urlscan-verify blocklist export",
    "===============================",
    "",
    `Generated ${report.generatedAt} from ${source}.`,
    `Included verdicts: ${severities.join(", ")}.`,
    `${hosts.length} hostname(s), ${ips.length} address(es).`,
    "",
    "Files",
    "-----",
    "domains.txt              plain list, one name per line",
    "dnsmasq-block.conf       drop in /etc/dnsmasq.d/ to blackhole these names",
    "hosts.txt                /etc/hosts style, for Pi-hole and friends",
    "dnsmasq-nftset.conf      OpenWrt 22.03+: feed resolved addresses into an nftables set",
    "dnsmasq-ipset.conf       OpenWrt 21.02 and older: same idea via ipset",
    "nftables-addresses.nft   the flagged addresses as an nft set",
    "pbr-policy.conf          a policy stanza for the OpenWrt pbr package",
    "",
    "Before you deploy",
    "-----------------",
    "Read domains.txt. These verdicts come from urlscan submitter tags plus",
    "structural analysis of the names themselves — useful, but not an audited",
    "threat feed. Anything you block here is a name your network stops reaching,",
    "so a false positive costs you a working service.",
    "",
  ].join("\n");

  return files;
}
